### ISSUE TITLE
Calculation Operation codes

### ISSUE THREAD

**Issue by JoaoCruzCx** [smeup/jariko#273]
Hi guys!

In the Lexer, the Fixed Calculation Operation code such as:

**CS_Operation_EXSR: OP_EXSR {this.Column>=29 && this.Column<36}? -> type(OP_EXSR);**

is using the token OP_EXSR. This token is only visible in the **OpCode** mode. How can **FIXED_CalcSpec** mode have access to this token?

Thank you!

**Comment by lanarimarco** [comment]
Hi, could you attach a simple use case in rpgle to clarify the issue?
Thanks in advance for your feedback.

Marco

**Comment by JoaoCruzCx** [comment]
C****************************************************************
     C* MAIN ROUTINE                                                 *
     C****************************************************************
     C*
     C                   EXSR      SR999
     C

**Comment by lanarimarco** [comment]
Your example is missing of subroutine body, and if Jariko tries to interpret this code, it will throw this exception: `Subroutine call not resolved: SR999`.
Grammar side, your code has no problem, but Jariko, after parsing, makes a syntax static check of the AST, and we will have a failure, just because of missing of the subroutine body.
If we fix it by adding the body:
```
     C****************************************************************
     C* MAIN ROUTINE                                                 *
     C****************************************************************
     C*
     C                   EXSR      SR999
     C
     C     SR999         BEGSR
     C     'OK'          DSPLY     
     C                   ENDSR
```
Jariko will interpret properly our code.
You should take in account that our goal is a good interpretation and coverage of rpg code, if you are more interested in general RPGLE grammar issues, you could take a look here: [rpgleparser](https://github.com/rpgleparser/rpgleparser).
